[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add remappings for installed libraries
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@uniswap/v4-core/=lib/v4-core/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options 